### ISSUE TITLE
No Attribute 'stanchion' error

### ISSUE THREAD

**Issue by emcconne** [basho-labs/ansible-riakcs#1]
This is an Ansible error that I'm having some trouble deciphering.  During the install I get the following on the "configure /etc/riak-cs/app.config" step in ansible-riakcs playbook...

TASK: [basho.riakcs | configure /etc/riak-cs/app.config] *********************\* 
<192.168.1.24> ESTABLISH CONNECTION FOR USER: root
<192.168.1.24> EXEC ['sshpass', '-d16', 'ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/emcconne/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '192.168.1.24', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1393017555.91-59612954171333 && echo $HOME/.ansible/tmp/ansible-1393017555.91-59612954171333'"]
fatal: [192.168.1.24] => {'msg': "One or more undefined variables: 'dict object' has no attribute 'stanchion'", 'failed': True}
fatal: [192.168.1.24] => {'msg': "One or more undefined variables: 'dict object' has no attribute 'stanchion'", 'failed': True}

FATAL: all hosts have already failed -- aborting

I don't even see a {{stanchion}} variable in the .j2 template so I'm a bit puzzled by why it's complaining.  Any ideas??

**Comment by emcconne** [comment]
See see now that the recipe requires a "stanchion" variable in the inventory file.

**Comment by jsmartin** [comment]
Sure, in etc_riak-cs_app.config.j2, there's a variable called: stanchion_ip.  By default, in the riakcs role, that is:

```
stanchion_ip: "{{ hostvars[groups['stanchion'][0]]['ansible_' + stanchion_iface]['ipv4']['address'] }}"
```

Which means you'll need to have a stantion group in your inventory if you are using the default value of stanchion_ip.  

See https://github.com/basho/ansible-riakcs/blob/develop/examples/hosts.
